# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvisUI(object):
    def setupUi(self, jarvisUI):
        jarvisUI.setObjectName("jarvisUI")
        jarvisUI.resize(1361, 746)
        jarvisUI.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(jarvisUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-320, -130, 1911, 1071))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(10, 10, 481, 321))
        self.bg_3.setStyleSheet("background-color: rgb(202, 15, 15);\n"
"background-color: rgb(112, 8, 1);")
        self.bg_3.setText("")
        self.bg_3.setObjectName("bg_3")
        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(500, 10, 851, 501))
        self.bg_2.setText("")
        self.bg_2.setPixmap(QtGui.QPixmap("../../G.U.I Material-20221121T175203Z-001/G.U.I Material/B.G/redbg.jpg"))
        self.bg_2.setScaledContents(True)
        self.bg_2.setObjectName("bg_2")
        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(10, 340, 481, 321))
        self.bg_4.setStyleSheet("background-color: rgb(202, 15, 15);\n"
"background-color: rgb(112, 8, 1);")
        self.bg_4.setText("")
        self.bg_4.setObjectName("bg_4")
        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(20, 20, 461, 301))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("../../G.U.I Material-20221121T175203Z-001/G.U.I Material/ExtraGui/live.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")
        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(20, 350, 461, 301))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("../../G.U.I Material-20221121T175203Z-001/G.U.I Material/ExtraGui/Code_Template.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")
        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(340, 290, 421, 291))
        self.gif_3.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));")
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("../../G.U.I Material-20221121T175203Z-001/G.U.I Material/B.G/Iron_Template_1.gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")
        self.text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_time.setGeometry(QtCore.QRect(700, 520, 211, 61))
        self.text_time.setStyleSheet("background-color: Transparent;\n"
"border-radius:none;\n"
"")
        self.text_time.setObjectName("text_time")
        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(910, 510, 231, 71))
        self.bg_5.setText("")
        self.bg_5.setPixmap(QtGui.QPixmap("../../G.U.I Material-20221121T175203Z-001/G.U.I Material/Buttons/button.jpeg"))
        self.bg_5.setScaledContents(True)
        self.bg_5.setObjectName("bg_5")
        self.bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.bg_6.setGeometry(QtCore.QRect(1140, 510, 221, 71))
        self.bg_6.setText("")
        self.bg_6.setPixmap(QtGui.QPixmap("../../G.U.I Material-20221121T175203Z-001/G.U.I Material/Buttons/button.jpeg"))
        self.bg_6.setScaledContents(True)
        self.bg_6.setObjectName("bg_6")
        self.bg_7 = QtWidgets.QLabel(self.centralwidget)
        self.bg_7.setGeometry(QtCore.QRect(680, 510, 241, 71))
        self.bg_7.setText("")
        self.bg_7.setPixmap(QtGui.QPixmap("../../G.U.I Material-20221121T175203Z-001/G.U.I Material/Buttons/button.jpeg"))
        self.bg_7.setScaledContents(True)
        self.bg_7.setObjectName("bg_7")
        self.text_day = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_day.setGeometry(QtCore.QRect(930, 520, 201, 61))
        self.text_day.setStyleSheet("background-color: Transparent;\n"
"border-radius:none;\n"
"")
        self.text_day.setObjectName("text_day")
        self.text_date = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_date.setGeometry(QtCore.QRect(1160, 520, 191, 51))
        self.text_date.setStyleSheet("background-color: Transparent;\n"
"border-radius:none;\n"
"")
        self.text_date.setObjectName("text_date")
        self.push_start = QtWidgets.QPushButton(self.centralwidget)
        self.push_start.setGeometry(QtCore.QRect(20, 680, 161, 41))
        self.push_start.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(225, 221, 217);\n"
"font: 75 22pt \"Courier New\";\n"
"border-radius:none;")
        self.push_start.setObjectName("push_start")
        self.bg_8 = QtWidgets.QLabel(self.centralwidget)
        self.bg_8.setGeometry(QtCore.QRect(10, 670, 481, 61))
        self.bg_8.setStyleSheet("background-color: rgb(202, 15, 15);\n"
"background-color: rgb(112, 8, 1);")
        self.bg_8.setText("")
        self.bg_8.setObjectName("bg_8")
        self.push_exit = QtWidgets.QPushButton(self.centralwidget)
        self.push_exit.setGeometry(QtCore.QRect(310, 680, 161, 41))
        self.push_exit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(225, 221, 217);\n"
"font: 75 22pt \"Courier New\";\n"
"border-radius:none;")
        self.push_exit.setObjectName("push_exit")
        self.bg_9 = QtWidgets.QLabel(self.centralwidget)
        self.bg_9.setGeometry(QtCore.QRect(730, 590, 621, 61))
        self.bg_9.setStyleSheet("background-color: rgb(202, 15, 15);\n"
"color: rgb(230, 255, 250);\n"
"font: 75 18pt \"Courier New\";\n"
"background-color: rgb(112, 8, 1);")
        self.bg_9.setText("")
        self.bg_9.setObjectName("bg_9")
        self.push_exit_2 = QtWidgets.QPushButton(self.centralwidget)
        self.push_exit_2.setGeometry(QtCore.QRect(710, 600, 631, 61))
        self.push_exit_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(225, 221, 217);\n"
"font: 75 18pt \"Courier New\";\n"
"border-radius:none;")
        self.push_exit_2.setObjectName("push_exit_2")
        self.label.raise_()
        self.bg_8.raise_()
        self.bg_2.raise_()
        self.bg_4.raise_()
        self.gif_2.raise_()
        self.gif_3.raise_()
        self.bg_3.raise_()
        self.gif_1.raise_()
        self.text_time.raise_()
        self.bg_5.raise_()
        self.bg_6.raise_()
        self.bg_7.raise_()
        self.text_day.raise_()
        self.text_date.raise_()
        self.push_start.raise_()
        self.push_exit.raise_()
        self.bg_9.raise_()
        self.push_exit_2.raise_()
        jarvisUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarvisUI)
        QtCore.QMetaObject.connectSlotsByName(jarvisUI)

    def retranslateUi(self, jarvisUI):
        _translate = QtCore.QCoreApplication.translate
        jarvisUI.setWindowTitle(_translate("jarvisUI", "MainWindow"))
        self.push_start.setText(_translate("jarvisUI", "START"))
        self.push_exit.setText(_translate("jarvisUI", "EXIT"))
        self.push_exit_2.setText(_translate("jarvisUI", "J.A.R.V.I.S - A Voice Assistant"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvisUI = QtWidgets.QMainWindow()
    ui = Ui_jarvisUI()
    ui.setupUi(jarvisUI)
    jarvisUI.show()
    sys.exit(app.exec_())
